import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, DM_Sans  } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import 'devicon/devicon.min.css'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-inter',
// })

const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-jetbrains',
})

export const metadata: Metadata = {
  title: "Eann Seth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jetbrains.variable} h-full dark antialiased `}
    >
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=jet-brains-mono@300&display=swap" rel="stylesheet"></link>
      </head>
      <body className="min-h-full flex flex-col bg-[#0a0a0f] font-['JetBrains_Mono',monospace]">
        <main>{children}</main>
        <Toaster position="top-center"/>
      </body>

    </html>
  );
}
